/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/setup': typeof SetupRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/setup': typeof SetupRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/setup': typeof SetupRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuisine'
    | '/dashboard'
    | '/menu'
    | '/setup'
    | '/super-admin'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuisine'
    | '/dashboard'
    | '/menu'
    | '/setup'
    | '/super-admin'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/cuisine'
    | '/dashboard'
    | '/menu'
    | '/setup'
    | '/super-admin'
    | '/admin/analytics'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuisineRoute: typeof CuisineRoute
  DashboardRoute: typeof DashboardRoute
  MenuRoute: typeof MenuRoute
  SetupRoute: typeof SetupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuisineRoute: CuisineRoute,
  DashboardRoute: DashboardRoute,
  MenuRoute: MenuRoute,
  SetupRoute: SetupRoute,
  SuperAdminRoute: SuperAdminRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
