/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuisine' | '/dashboard' | '/menu' | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuisine' | '/dashboard' | '/menu' | '/admin/login'
  id: '__root__' | '/' | '/cuisine' | '/dashboard' | '/menu' | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuisineRoute: typeof CuisineRoute
  DashboardRoute: typeof DashboardRoute
  MenuRoute: typeof MenuRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuisineRoute: CuisineRoute,
  DashboardRoute: DashboardRoute,
  MenuRoute: MenuRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
